# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sicheng Jia
email: jsicheng@hotmail.com
description: Website for Sicheng Jia
icon: "/assets/images/mako.jpg"
repository: "jsicheng/jsicheng.github.io"
masthead_title: "Home"


minimal_mistakes_skin: "air" #default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# # Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sicheng Jia"
  avatar : "/assets/images/mako.jpg"
  bio    : "Second year MS student in Computer Science at UCLA.\n\n
  Former TA for CS 31, CS M51A and\n CS 111.
  "
  
  links:
    - label: "jsicheng@hotmail.com"
      icon: "fas fa-fw fa-at"
      url: "mailto:jsicheng@hotmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jsicheng.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jsicheng"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jsicheng/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sichen_gg"

footer:
  links:
    - label: "jsicheng@hotmail.com"
      icon: "fas fa-fw fa-at"
      url: "mailto:jsicheng@hotmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jsicheng.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jsicheng"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/jsicheng/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram-square"
      url: "https://instagram.com/sichen_gg"
atom_feed:
  hide: true

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
